services:
  dev:
    build: .
    ports:
      - "3000:3000"     # Vercel Dev Interface
      - "24678:24678"   # WebSocket Vite (HMR) for Resend
    volumes:
      - .:/portfolio
      - /portfolio/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=1024
      - WATCHPACK_POLLING=true
      - VERCEL_TELEMETRY_DISABLED=1
    deploy:
      resources:
        limits:
          memory: 1024M
